version: 2.1

orbs:
  python: circleci/python@1.3.2

executors:
  py2exec:
    description: Image for Python 2
    docker:
      - image: 'cimg/python:2.7'
        # auth is now set up using a context in the workflow job
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD

jobs:
  build:
    executor: py2exec
    steps:
      - checkout
      - run: echo "Using dockerhub user = $DOCKERHUB_USER"
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: dev-requirements.txt

#    - run:
#      command: ./manage.py test
#      name: Test
  
workflows:
  main:
    jobs:
    - build:
        context:
          - geophphrie
