version: 2.1

orbs:
  python: circleci/python@1.3.2

executors:
  py2exec:
    description: Image for Python 2
    docker:
      - image: 'cimg/python:2.7'
        auth:
          username: geophphrie
          password: $DOCKERHUB_PASSWORD

jobs:
  build:
    executor: py2exec
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: dev-requirements.txt

#    - run:
#          command: ./manage.py test
#          name: Test
  
workflows:
  main:
    jobs:
      - build

