version: 2.1

orbs:
  python: circleci/python@

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
          pip-dependency-file: dev-requirements.txt
	  version: 2.7
      - python/save-cache

#    - run:
#          command: ./manage.py test
#          name: Test

workflows:
  main:
    jobs:
      - build-and-test
